global:
  domain: argocd.talrozen.com

configs:
  params:
    server.insecure: true
  secret:
    githubSecret: LXdlYmhvb2stc2VjcmV0OndlYmhvb2suZ2l0aHViLnNlY3JldA==

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true

  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    tls: true
