apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCMjl6bz6iVTJJqn6LzdYnQ3v5kxNHS9az+sQLzpIWi+biq4TM4WnnPWvKD5Tf5qUIQb/NPxqruUbNza47iRJ0T3iiMgEhQxhUubjs2JpSzvOCWYnW38EDmEpHruJ19I/ihVJBPzE1IMjRVrFVtAcpMDPgDZX5M0iz4zXCYey7NQX68l0w/wzfV32yfIqWWVxwXcOoh3/0aZ40taKXu5ASCJRt7uF71sjVy4DE8liqXxsKUD5kI+pi8IGHOcUPeCnqnyCULzDMLm6Sv6gz6no5MvSvKGBOvxza4T3LHaUth1yTa6bnnIBa5Pp6hOuj4PJdm4wkVtKBqwcuuY7vLxe4fEg0VMSZARaBH2tJKgY5DWA6dq03H+aezAdCecjpF8zixZRbxM3HVHqIOSkl2pYMTtN7ehgaNwFTjq4m7AhW+YeZc3ZS94If+9dwxwOp/sAeniWHK2dJrLCFppkS7X0Pn/kLMGaWfrJfL+ngk/S7Te5f6+q+ug0r6DQyWVWkAhWk4N5OwUd4RpwTRkWwceXhkL7RQDV35xn2Up9Da190+tUB5h+66jBbkhTbYQfqNyCaAW8p+5I+9k5BAbsQ9hxUb1EyZQPE49H1nY7mhuaU7zKizd6KjhlvKkO2chXKiIZIu/BvBzlbGPOazYSh0lnAn5cqTxEgRNTgocV2YAJqlc48xcDW/kX96Gu9An5wY0qcnW3reWqEXgw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor
    type: Opaque

