apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgBRb0aW1bgsGDNW70msbswXtveb2go9ptQLhiSSmdKhRUYVUqtjmdllzT/4Z6leo+Fzpd1SqCp3CJgouhpzt6O0mT9k7GcFhZu3Kl5POXjlC/jopRdD/kxQ2vmacJv4hAtWtCFXmA0DqRhAdhmxulcAzqAYRiCpr926kNLnQhrlvIcuY2/I5iD6PM54w61TpltoyjoRDM4uirv/N4UUckLwdF9qHRK7wNQFr+jxbkA5YF3uO7Efr8yD7TSaSJcHmJftQBwzXV42fNkFuMs+dZGyARVCGJCZ2xH0tRmWEjICXhh73v/YiWV/QaCTzjsJ0/R2HVc3Al8BJvznuUlSC6Z2ZKGWZi0m5AmAtPbtYwC5QULY16R6a4zQjIwC+QA7angafMuVMtWUfTkcBdehZBjNEyolJiVGhQ7/0gNRz9jGqthCiu15ZHlyCCFrUKIoYfJr1/xn98nuENWPtnFUZ3N9G1G4mL91qDq+ysUsUo1MnXY/rwgP9DZ4otD8ZK1i+y0kC/W2lNu1UNhoDezhHzPWrANoy/FIEWWvZG5sIFX/bVI4A/IaoLes2SIQt89Z13muA0lcjmFyrgLyUIi3KnNLvgUl5zpVyT8mg4jC1ONsk9b736rNj4iTo+8dGhLLEfibYYZraP52esATawo/p236zNySBhVXbuISTk4tRUqNcn5jx/6lb+6dIKjeBmQ1MtrSjSUcTfMK9w==
    jenkins-admin-user: AgCCXLCLfbLajIjZK1Y6gWMLuY7JtFncHgYL5c2HeXOLolm7bfi5+XFBbQkN71hED8hDoGcZf2QFIALbRvTEZZCWrCZYsBDvYzmv5YH1rlMaofZjvp7yu9SjN8Hf5VDgZoahh84KLvyQwQ6zovmvTT6QaoN/WGGcuPdosGhtuxzR3x2Qr2AtzwJVxSJbrACut8x27VrYUGK2ck/8YPPTFRRAuMF1w9IPQRPq6+8mTWS1Z8aDp2Utu1eKsaBop4cqYe9cG/ujVa5cOgJgUTZ4ZRiV1NXoa1H0tP8ndIXhVFyLhG9PvRpKOFH4bsms55ecpN0xltxCVn4qqgvWJo4wXtFBmvRjPEVJDu4eO1yfGexHt5eIvKzAk/KoiWurVKXsuf32cGZ3fvJkmrLAbYChG7KI1d71Meuorh5XCXhw4UzU3Huyj0KvrHcbmkYuRRzkmXNgsWsve02l2+EJM/GxlNxJVD2TqqoD5K3zWgAN/mcYwM+LuZDgW+LvBPRjhhD9mByo3XfDwJC3wnQPV6G92huT5sICNR1d9j9nbsbxo1R64gZ2voN3+YdPQTbR/j4fKZ6z+Hz5HEuK5gJKMvTePwIp/u9PAuqjrsJUaKz6TlOmvLEwYfysY82hpqciVEl5znsusf1RdNc60pn/uOq6pGzjnY17EubENw+Ng1O8UNfLo04MJONnRC0dwAEULtrR9lQ82vAuXA==
  template:
    metadata:
      creationTimestamp: null
      name: jenkins-admin-secret
      namespace: jenkins
    type: Opaque
