controller:
  admin:
    existingSecret: "jenkins-admin-secret"
    userKey: "jenkins-admin-user"
    passwordKey: "jenkins-admin-password"
  
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - ws-cleanup
    - job-dsl
    - docker-plugin
    - envinject
    - docker-workflow
    - generic-webhook-trigger
    - kubernetes-credentials-provider
    - pipeline-utility-steps

  JCasC:
    enabled: true
    configScripts:
      disable-dsl-security: |
        security:
          globalJobDslSecurityConfiguration:
            useScriptSecurity: false
      
      configure-webhook-hmac-secret: |
        unclassified:
          whitelist:
            enabled: true
            whitelistItems:
            - hmacAlgorithm: "HmacSHA256"
              hmacCredentialId: "github-webhook-secret"
              hmacEnabled: true
              hmacHeader: "X-Hub-Signature-256"


  ingress:
    enabled: true
    hostName: "jenkins.talrozen.com"
    ingressClassName: nginx
    tls:
      - secretName: cloudflare-tls
        hosts:
          - jenkins.talrozen.com

rbac:
  create: true
  readSecrets: true

persistence:
  enabled: true
  storageClass: "nfs-client"

agent:
  podTemplates:
    k8sWithDocker: |
      - name: k8swithdocker
        label: K8S-With-Docker
        serviceAccount: default
        containers:
          - name: jnlp
            image: harbor.talrozen.com/jenkins/docker-agent:1.0.1
            envVars:
              - envVar:
                  key: "JENKINS_URL"
                  value: "http://jenkins.jenkins.svc.cluster.local:8080/"
        namespace: jenkins
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        runAsUser: 1000
        podRetention: "Never"
        slaveConnectTimeout: 100
        imagePullSecrets:
          - name: "agent-pull-secret"
